//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inversions.ClassesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesglosCompra
    {
        public int Id { get; set; }
        public int MovCompraId { get; set; }
        public int MovCompraOrigId { get; set; }
        public decimal Participacions { get; set; }
        public decimal ParticipacionsOrig { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Moviment MovCompra { get; set; }
        public virtual Moviment MovCompraOrig { get; set; }
    }
}
