//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inversions.ClassesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.Gestors = new HashSet<Gestor>();
            this.Productes = new HashSet<Producte>();
        }
    
        public int Id { get; private set; }
        public string Nom { get; set; }
        public TipusEmpresa TipusEmpresa { get; set; }
        public byte[] RowVersion { get; private set; }
    
        public virtual ICollection<Gestor> Gestors { get; set; }
        public virtual ICollection<Producte> Productes { get; set; }
    }
}
