//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inversions.ClassesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gestor
    {
        public Gestor()
        {
            this.ProdFons = new HashSet<ProdFons>();
        }
    
        public int Id { get; private set; }
        public int EmpresaId { get; private set; }
        public Nullable<int> ProducteId { get; private set; }
        public string Nom { get; set; }
        public byte[] RowVersion { get; private set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<ProdFons> ProdFons { get; set; }
    }
}
