//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inversions.ClassesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresExtern
    {
        public int Id { get; set; }
        public int UsuariId { get; set; }
        public short Any { get; set; }
        public string Rao { get; set; }
        public decimal Import { get; set; }
    
        public virtual Usuari Usuari { get; set; }
    }
}
