//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inversions.ClassesEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InversionsBDContext : DbContext
    {
        public InversionsBDContext()
            : base("name=InversionsBDContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empresa> Empreses { get; set; }
        public virtual DbSet<Gestor> Gestors { get; set; }
        public virtual DbSet<Valoracio> Valoracions { get; set; }
        public virtual DbSet<Producte> Productes { get; set; }
        public virtual DbSet<Mercat> Mercats { get; set; }
        public virtual DbSet<Usuari> Usuaris { get; set; }
        public virtual DbSet<Moviment> Moviments { get; set; }
        public virtual DbSet<DesglosCompra> DesglosCompres { get; set; }
        public virtual DbSet<IngresExtern> IngressosExterns { get; set; }
    }
}
