//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inversions.ClassesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mercat
    {
        public Mercat()
        {
            this.ProdAccions = new HashSet<ProdAccions>();
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
        public byte[] RowVersion { get; private set; }
    
        public virtual ICollection<ProdAccions> ProdAccions { get; set; }
    }
}
