//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inversions.ClassesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monedes
    {
        public Monedes()
        {
            this.Productes = new HashSet<Producte>();
        }
    
        public string Codi { get; set; }
        public string Ticker { get; set; }
        public string Descripcio { get; set; }
    
        public virtual ICollection<Producte> Productes { get; set; }
    }
}
