//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inversions.ClassesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moviment
    {
        public Moviment()
        {
            this.RefTraspas1 = new HashSet<Moviment>();
            this.DesglosCompres = new HashSet<DesglosCompra>();
            this.DesglosCompresOrig = new HashSet<DesglosCompra>();
        }
    
        public int Id { get; set; }
        public int UsuariId { get; set; }
        public int ProdId { get; set; }
        public TipusMoviment TipusMoviment { get; set; }
        public Nullable<int> RefTraspasId { get; set; }
        public System.DateTime Data { get; set; }
        public decimal Participacions { get; set; }
        public decimal PreuParticipacio { get; set; }
        public decimal CanviAplicat { get; set; }
        public Nullable<decimal> Despeses { get; set; }
        public Nullable<decimal> PiGVendaReal { get; set; }
        public string Descripcio { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Producte Prod { get; set; }
        public virtual ICollection<Moviment> RefTraspas1 { get; set; }
        public virtual Moviment RefTraspas { get; set; }
        public virtual Usuari Usuari { get; set; }
        public virtual ICollection<DesglosCompra> DesglosCompres { get; set; }
        public virtual ICollection<DesglosCompra> DesglosCompresOrig { get; set; }
    }
}
