//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inversions.ClassesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdFons : Producte
    {
        public ProdFons()
        {
            this.Gestors = new HashSet<Gestor>();
        }
    
        public string Nom { get; set; }
        public string ISIN { get; set; }
        public TipusFons Tipus { get; set; }
        public string Descripcio { get; set; }
    
        public virtual ICollection<Gestor> Gestors { get; set; }
    }
}
