//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inversions.ClassesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdAccions : Producte
    {
        public int MercatId { get; set; }
    
        public virtual Mercat Mercat { get; set; }
    }
}
