//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inversions.ClassesEntity
{
    using System;
    
    public enum TipusMoviment : int
    {
        Compra = 0,
        Venda = 1,
        Dividends = 2,
        Traspàs = 3,
        Split = 4,
        ContraSplit = 5
    }
}
