//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inversions.ClassesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuari
    {
        public Usuari()
        {
            this.Moviments = new HashSet<Moviment>();
            this.IngressosExterns = new HashSet<IngresExtern>();
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
    
        public virtual ICollection<Moviment> Moviments { get; set; }
        public virtual ICollection<IngresExtern> IngressosExterns { get; set; }
    }
}
