//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inversions.ClassesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valoracio
    {
        public int Id { get; private set; }
        public int ProdId { get; set; }
        public System.DateTime Data { get; set; }
        public decimal PreuParticipacio { get; set; }
        public byte[] RowVersion { get; private set; }
    
        public virtual Producte Prod { get; set; }
    }
}
